# postgres-db.yaml

# 1. This is the PersistentVolumeClaim (the K8s version of your "pgdata" volume)
# It requests 1GB of storage from Minikube.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce # This volume can be mounted by one pod at a time
  resources:
    requests:
      storage: 1Gi # You can change this size if needed

---

# 2. This is the Service (the stable network hostname "postgres-db-service")
# Your Spring app will use this name to find the database.
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
spec:
  ports:
    - port: 5432
  selector:
    app: postgres # Connects this service to the pods labeled "app: postgres"

---

# 3. This is the Deployment (runs the Postgres container)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres # Must match the service's selector
    spec:
      containers:
        - name: postgres
          image: postgres:16 # <-- UPDATED from your compose file
          ports:
            - containerPort: 5432
          env:
            # --- UPDATED from your compose file ---
            - name: POSTGRES_DB
              value: "car_db"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "password" # <-- See security note below
            # --------------------------------------
          volumeMounts:
            # This mounts the volume into the container
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        # This links the pod to the PersistentVolumeClaim
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc